### PR TITLE
#68 README

### PR DESCRIPTION
**Pull request by michalmikolajczyk**
Resolves: #68

### CODE REVIEW

**Comment by paalex** [comment]
@michalmikolajczyk that is great.
The only thing I'm not sure about is that the developer would be able to assign an issue to themself without first joining as an editor. Could they?

**Comment by michalmikolajczyk** [comment]
@paalex yea I think so... I am not a member of the organization and I have issues assigned to me

**Comment by michalmikolajczyk** [comment]
@paalex we seem to have two files with the env vars: `.env.example` and `.env.sample`

I think we can just provide the web map id? It seems to me it's public anyway on https://geobel.online

Should we merge them together?

**Comment by paalex** [comment]
@michalmikolajczyk i don't see any value in putting our map id there. 
Whoever uses it in the future need to understand they would need to find their own map id

**Pull request merged**
